/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import controllers.CargarPreguntas;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.event.*;
import javax.swing.text.*;
import javax.swing.text.BadLocationException;
//import components.DocumentSizeFilter;

/**
 *
 * @author user
 */
public class FrmCargarPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form EditorTexto
     */
    private DefaultStyledDocument preg, resp;
    private CargarPreguntas pc = new CargarPreguntas();
    private boolean clickCP=false;
    private boolean clickCR=false;
    private CargarPreguntas rc = new CargarPreguntas();

    public FrmCargarPreguntas() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        preg = new DefaultStyledDocument();
        preg.addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                updateCount();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateCount();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateCount();
            }
        });
        txtAreaPregunta.setDocument(preg);
        updateCount();
        resp = new DefaultStyledDocument();
        resp.addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                updateCountResp();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateCountResp();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateCountResp();
            }
        });
        this.txtAreaRes.setDocument(resp);
        updateCountResp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPregunta = new javax.swing.JTextArea();
        btnCorregirPreg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCaracUsaP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgEx = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaCorreccionPreg = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaRes = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaCorreccionRes = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        lblCaracUsaR = new javax.swing.JLabel();
        btnCorregirRes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAreaPregunta.setColumns(20);
        txtAreaPregunta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAreaPregunta.setLineWrap(true);
        txtAreaPregunta.setRows(5);
        jScrollPane1.setViewportView(txtAreaPregunta);

        btnCorregirPreg.setText("Corregir");
        btnCorregirPreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorregirPregActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Recuerda que la Pregunta no debe poseer errores ortográficos ni sintácticos.");

        lblCaracUsaP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCaracUsaP.setForeground(new java.awt.Color(0, 0, 204));
        lblCaracUsaP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCaracUsaP.setText("140");

        jLabel4.setText("Cantidad de Caracteres Usados ");

        btnAgEx.setText("Agregar Pregunta y Respuesta");
        btnAgEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgExActionPerformed(evt);
            }
        });

        jLabel1.setText("RESPUESTA A LA PREGUNTA PLANTEADA ARRIBA");

        txtAreaCorreccionPreg.setColumns(20);
        txtAreaCorreccionPreg.setRows(5);
        txtAreaCorreccionPreg.setEnabled(false);
        jScrollPane2.setViewportView(txtAreaCorreccionPreg);

        txtAreaRes.setColumns(20);
        txtAreaRes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAreaRes.setLineWrap(true);
        txtAreaRes.setRows(5);
        jScrollPane4.setViewportView(txtAreaRes);

        txtAreaCorreccionRes.setColumns(20);
        txtAreaCorreccionRes.setRows(5);
        txtAreaCorreccionRes.setEnabled(false);
        jScrollPane5.setViewportView(txtAreaCorreccionRes);

        jLabel5.setText("Cantidad de Caracteres Usados ");

        lblCaracUsaR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCaracUsaR.setForeground(new java.awt.Color(0, 0, 204));
        lblCaracUsaR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCaracUsaR.setText("140");

        btnCorregirRes.setText("Corregir");
        btnCorregirRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorregirResActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                        .addGap(172, 172, 172))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAgEx))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCaracUsaR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCorregirRes)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCaracUsaP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCorregirPreg)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCaracUsaP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCorregirPreg))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCaracUsaR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCorregirRes))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgEx, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCorregirPregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorregirPregActionPerformed
        try {
            pc.corregir(this.txtAreaPregunta, this.txtAreaCorreccionPreg);
            
        } catch (IOException ex) {
            Logger.getLogger(FrmCargarPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BadLocationException ex) {
            Logger.getLogger(FrmCargarPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCorregirPregActionPerformed

    private void btnAgExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgExActionPerformed

        if (pc.getHayErrores() == false && rc.getHayErrores()==false) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "La pregunta a agregar es: " + txtAreaPregunta.getText()+". La respuesta es: "+ this.txtAreaRes.getText(), "ATENCIÓN", OK_CANCEL_OPTION);
            if (dialogResult == JOptionPane.OK_OPTION) {
                if(rc.cargarPregunta(this.txtAreaPregunta, this.txtAreaRes)==true){
                    JOptionPane.showMessageDialog(this, "Pregunta y respuesta cargada con éxito");
                    this.dispose();
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "No deben haber errores ortográficos y tanto la pregunta como la respuestas deben ser validados al menos una vez");
        }


    }//GEN-LAST:event_btnAgExActionPerformed

    private void btnCorregirResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorregirResActionPerformed
        try {
            rc.corregir(this.txtAreaRes, this.txtAreaCorreccionRes);
        } catch (IOException ex) {
            Logger.getLogger(FrmCargarPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BadLocationException ex) {
            Logger.getLogger(FrmCargarPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCorregirResActionPerformed
    private void updateCountResp() {
        // this.lblCaracUsaR.setText(Integer.toString(resp.getLength()));
        lblCaracUsaR.setText(Integer.toString(resp.getLength()));
        rc.setHayErrores(true);
    }

    private void updateCount() {
        // this.lblCaracUsaR.setText(Integer.toString(resp.getLength()));
        lblCaracUsaP.setText(Integer.toString(preg.getLength()));
        pc.setHayErrores(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCargarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCargarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCargarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCargarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmCargarPreguntas().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgEx;
    private javax.swing.JButton btnCorregirPreg;
    private javax.swing.JButton btnCorregirRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCaracUsaP;
    private javax.swing.JLabel lblCaracUsaR;
    private javax.swing.JTextArea txtAreaCorreccionPreg;
    private javax.swing.JTextArea txtAreaCorreccionRes;
    private javax.swing.JTextArea txtAreaPregunta;
    private javax.swing.JTextArea txtAreaRes;
    // End of variables declaration//GEN-END:variables
}
