/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import components.DocumentSizeFilter;
import components.LeerPregunta;
import controllers.EditorTexto;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.event.*;
import javax.swing.text.*;
import javax.swing.text.BadLocationException;
//import components.DocumentSizeFilter;

/**
 *
 * @author user
 */
public class FrmCargarPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form EditorTexto
     */
      
     private DefaultStyledDocument doc;
      
    public FrmCargarPreguntas()  {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        setLocationRelativeTo(null);
       
         doc = new DefaultStyledDocument();
    
        doc.addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                updateCount();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateCount();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateCount();
            }
        });
        txtAreaPregunta.setDocument(doc);
        

        updateCount();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPregunta = new javax.swing.JTextArea();
        btnSiguiente = new javax.swing.JButton();
        btnCorregir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCaracRest = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgEx = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaRespuesta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAreaPregunta.setColumns(20);
        txtAreaPregunta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAreaPregunta.setLineWrap(true);
        txtAreaPregunta.setRows(5);
        jScrollPane1.setViewportView(txtAreaPregunta);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.setEnabled(false);

        btnCorregir.setText("Corregir");
        btnCorregir.setEnabled(false);
        btnCorregir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorregirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Recuerda que la Pregunta no debe poseer errores ortográficos ni sintácticos.");

        lblCaracRest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCaracRest.setForeground(new java.awt.Color(0, 0, 204));
        lblCaracRest.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCaracRest.setText("140");

        jLabel4.setText("Cantidad de Caracteres ");

        btnAgEx.setText("Agregar Pregunta y respuesta");
        btnAgEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgExActionPerformed(evt);
            }
        });

        jLabel1.setText("RESPUESTA A LA PREGUNTA PLANTEADA ARRIBA");

        txtAreaRespuesta.setColumns(20);
        txtAreaRespuesta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAreaRespuesta.setLineWrap(true);
        txtAreaRespuesta.setRows(5);
        jScrollPane3.setViewportView(txtAreaRespuesta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 294, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCaracRest, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCorregir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSiguiente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgEx)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnCorregir)
                    .addComponent(lblCaracRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgEx, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCorregirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorregirActionPerformed
        try {
            EditorTexto et = new EditorTexto();
            et.corregirPregunta(txtAreaPregunta);
        } catch (IOException ex) {
            Logger.getLogger(FrmCargarPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BadLocationException ex) {
            Logger.getLogger(FrmCargarPreguntas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCorregirActionPerformed
    
    private void btnAgExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgExActionPerformed
        try {
            EditorTexto et = new EditorTexto();
            et.corregirPregunta(txtAreaPregunta);
            et.corregirPregunta(txtAreaRespuesta);
            if (et.corregirPregunta(txtAreaPregunta) == 0 && et.corregirPregunta(txtAreaRespuesta) == 0) {
                int dialogResult = JOptionPane.showConfirmDialog(null, "La Pregunta a agregar es: " + txtAreaPregunta.getText(), "ATENCIÓN", OK_CANCEL_OPTION);
                if (dialogResult == JOptionPane.OK_OPTION) {
                    try {

                        BufferedWriter ofile;
                        ofile = new BufferedWriter(new FileWriter("Preguntas.txt", true));
                        ofile.newLine();
                        ofile.append("\n" + txtAreaPregunta.getText());                        
                        ofile.close();
                        BufferedWriter ofile2;

                        ofile2 = new BufferedWriter(new FileWriter("Respuestas.txt", true));
                        ofile2.newLine();
                        ofile2.append("\n" + txtAreaRespuesta.getText());                        
                        ofile2.close();

//                p.closeChild(this);
                    } catch (IOException ex) {
                        Logger.getLogger(FrmAgregarExcepcion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(FrmEditorTexto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BadLocationException ex) {
            Logger.getLogger(FrmEditorTexto.class.getName()).log(Level.SEVERE, null, ex);
        }

//        ae.setPadre(this);
    }//GEN-LAST:event_btnAgExActionPerformed
  
//    public void closeChild(){
//        ae.dispose();
//    }
     private void updateCount() {
       
        lblCaracRest.setText(Integer.toString(doc.getLength()));
    }

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCargarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCargarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCargarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCargarPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmCargarPreguntas().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgEx;
    private javax.swing.JButton btnCorregir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCaracRest;
    private javax.swing.JTextArea txtAreaPregunta;
    private javax.swing.JTextArea txtAreaRespuesta;
    // End of variables declaration//GEN-END:variables
}
